# Generated by Django 4.1.7 on 2023-04-04 07:02

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='image',
        ),
        migrations.AddField(
            model_name='tip',
            name='image_url',
            field=models.ImageField(default=None, upload_to=tips.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='favorite_count',
            field=models.IntegerField(blank=True, choices=[(1, 'Yoga/Stretching'), (2, 'Diet/Supplements'), (3, 'Lifestyle/Other')], default=False, null=True),
        ),
    ]
