# Generated by Django 4.1.7 on 2023-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_remove_tip_image_tip_image_url_alter_tip_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='favorite_count',
            field=models.IntegerField(blank=True, choices=[(1, 'Yoga/Stretching'), (2, 'Diet/Supplements'), (3, 'Lifestyle/Other')], null=True),
        ),
    ]
