# Generated by Django 4.1.7 on 2023-04-21 19:22

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_tip_category_alter_tip_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=tips.models.upload_to),
        ),
        migrations.AlterField(
            model_name='tip',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(),
        ),
    ]
