# Generated by Django 4.1.7 on 2023-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_home_park_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_park',
            field=models.CharField(default='NaN', max_length=40),
        ),
    ]
